also need 32bit gcc for 32bit prefix

diff --git a/docker/Dockerfile.fedora28 b/docker/Dockerfile.fedora28
--- a/docker/Dockerfile.fedora28
+++ b/docker/Dockerfile.fedora28
@@ -1,12 +1,30 @@
 
 FROM fedora:28
 
-# make             # stage1 make fails with https://bugs.gentoo.org/646558
+ARG BOOTSTRAP_OPTS
+
+# gcc-c++                     # would install "gcc-c++.x86_64", but:
+# gcc-c++        gcc-c++.i686 # would install "gcc-c++.i686" only, so need:
+# gcc-c++.x86_64 gcc-c++.i686 # to install both, but both just depend on:
+# libstdc++-devel             # without their specific arch - need both
 # glibc-devel.i686 # python does look for /usr/lib/libcrypt.so file only
-RUN set -e \
+# make             # stage1 make fails with https://bugs.gentoo.org/646558
+RUN set -x \
+  ; set -e \
   ; dnf check-update || : \
-  ; dnf install -y gcc-c++ wget sudo \
-  ; dnf install -y make glibc-devel.i686 \
+  ; pkgs="gcc-c++.x86_64 libstdc++-devel.x86_64" \
+  ; for arg in ${BOOTSTRAP_OPTS} \
+  ; do case ${arg} in \
+       --force-32bit=yes) : \
+	     ; pkgs="${pkgs} gcc-c++.i686 libstdc++-devel.i686" \
+		 ;; \
+	   esac \
+  ; done \
+  ; pkgs="${pkgs} wget" \
+  ; pkgs="${pkgs} sudo" \
+  ; pkgs="${pkgs} glibc-devel.i686" \
+  ; pkgs="${pkgs} make" \
+  ; dnf install -y ${pkgs} \
   ; :
 
 ENV SUDO_GROUP wheel
diff --git a/docker/Dockerfile.opensuse b/docker/Dockerfile.opensuse
--- a/docker/Dockerfile.opensuse
+++ b/docker/Dockerfile.opensuse
@@ -1,12 +1,27 @@
 
 FROM opensuse
 
-# make              # stage1 make fails with https://bugs.gentoo.org/646558
+ARG BOOTSTRAP_OPTS
+
 # glibc-devel-32bit # python does look for /usr/lib/libcrypt.so file only
-RUN set -e \
+# make              # stage1 make fails with https://bugs.gentoo.org/646558
+RUN set -x \
+  ; set -e \
   ; zypper --non-interactive update \
-  ; zypper --non-interactive install gcc-c++ wget tar sudo \
-  ; zypper --non-interactive install make glibc-devel-32bit \
+  ; pkgs="gcc-c++" \
+  ; for arg in ${BOOTSTRAP_OPTS} \
+  ; do case ${arg} in \
+       --force-32bit=yes) : \
+	     ; pkgs="${pkgs} gcc-c++-32bit" \
+		 ;; \
+	   esac \
+  ; done \
+  ; pkgs="${pkgs} wget" \
+  ; pkgs="${pkgs} tar" \
+  ; pkgs="${pkgs} sudo" \
+  ; pkgs="${pkgs} glibc-devel-32bit" \
+  ; pkgs="${pkgs} make" \
+  ; zypper --non-interactive install ${pkgs} \
   ; :
 
 ENV SUDO_GROUP wheel
diff --git a/docker/Dockerfile.ubuntu b/docker/Dockerfile.ubuntu
--- a/docker/Dockerfile.ubuntu
+++ b/docker/Dockerfile.ubuntu
@@ -1,10 +1,24 @@
 
 FROM ubuntu
 
-# make           # stage1 make fails with https://bugs.gentoo.org/646558
+ARG BOOTSTRAP_OPTS
+
 # libc6-dev-i386 # python does look for /usr/lib/libcrypt.so file only
-RUN set -e \
+# make           # stage1 make fails with https://bugs.gentoo.org/646558
+RUN set -x \
+  ; set -e \
   ; apt-get update \
-  ; apt-get install -y g++ wget sudo \
-  ; apt-get install -y make libc6-dev-i386 \
+  ; pkgs="g++" \
+  ; for arg in ${BOOTSTRAP_OPTS} \
+  ; do case ${arg} in \
+       --force-32bit=yes) \
+	     pkgs="g++-multilib" \
+	     ;; \
+	   esac \
+  ; done \
+  ; pkgs="${pkgs} wget" \
+  ; pkgs="${pkgs} sudo" \
+  ; pkgs="${pkgs} libc6-dev-i386" \
+  ; pkgs="${pkgs} make" \
+  ; apt-get install -y ${pkgs} \
   ; :
